# Generated by Django 3.1.2 on 2021-06-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210626_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
