# Generated by Django 3.1.2 on 2021-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210626_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=10000, verbose_name='Tannarxi'),
            preserve_default=False,
        ),
    ]
