# Generated by Django 3.1.2 on 2021-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('count', models.PositiveIntegerField(verbose_name='Soni')),
                ('unit', models.CharField(max_length=15, verbose_name='Birlik')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=15, verbose_name='Birlik'),
            preserve_default=False,
        ),
    ]
