# Generated by Django 3.1.2 on 2021-06-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255, verbose_name='Asos')),
                ('summa', models.PositiveIntegerField(verbose_name='Summa')),
                ('closed', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('variation', models.CharField(choices=[('debit', 'Debitor'), ('kredit', 'Kreditor')], max_length=15)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Hamkor')),
            ],
        ),
    ]
