# Generated by Django 3.1.2 on 2021-07-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(verbose_name='Summa')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partner.partner', verbose_name='Hamkor')),
            ],
        ),
    ]
