# Generated by Django 3.1.2 on 2021-07-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210701_1052'),
        ('trade', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.PositiveIntegerField(default=2, verbose_name='Soni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AddField(
            model_name='purchase',
            name='raw',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='product.raw', verbose_name='Xomashyo'),
            preserve_default=False,
        ),
    ]
