# Generated by Django 3.1.2 on 2021-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=998999999999, max_length=50, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
