# Generated by Django 3.1.2 on 2021-06-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(verbose_name='Summa')),
                ('base', models.CharField(max_length=255, verbose_name='Asos')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partner.partner', verbose_name='Hamkor')),
            ],
        ),
    ]
