# Generated by Django 3.1.2 on 2021-06-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('product', '0003_auto_20210626_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Soni')),
                ('paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('summa', models.PositiveIntegerField(verbose_name='Summa')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partner.partner', verbose_name='Hamkor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Maxsulot')),
            ],
        ),
    ]
